name: Report Bug
description: Help us improve by reporting a bug
labels: ['🐛 bug']
body:
  - type: textarea
    id: description
    attributes:
      label: 📝 Description,
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 🎯 Expected Behavior,
      description: A clear and concise description of what you expected to happen.
      placeholder: e.g. It should export a JSON file when clicking the button.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: 🚫 Actual Behavior,
      description: A clear and concise description of what actually happened.
      placeholder: e.g. It just does not work when clicked.
    validations:
      required: true
  - type: checkboxes
    id: browsers
    attributes:
      label: Browser,
      description: In which browser(s) are you experiencing the issue? You may select more than one.
      options:
        - label: Chrome/Chromium,
        - label: Firefox,
        - label: Safari,
        - label: Edge,
        - label: Opera,
        - label: Kiwi,
        - label: SPIN,
        - label: Brave,
        - label: Other/not relevant
    validations:
      required: true
  - type: checkboxes
    id: operating-systems
    attributes:
      label: Operating system,
      description: In which operating systems are you experiencing the issue? You may select more than one.
      options:
        - label: Windows,
        - label: Linux,
        - label: macOS,
        - label: iOS,
        - label: Android,
        - label: Other/not relevant
    validations:
      required: true
  - type: textarea
    id: stepsToReproduce
    attributes:
      label: Steps to reproduce,
      description: Please provide a detailed guide on how this issue can be reproduced.
      placeholder: |
        1. I opened the modal by clicking the more button.
        2. I clicked on the export JSON button.
        ...
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist,
      description: Please review the following checklist before submitting your issue.
      options:
        - label: I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
          required: true
    validations:
      required: true
